Repository autovance/ftp-srv, pull requests merged in 2019-02, with the labels that each got.

#151 feat: expose a RNTO event
  README.md
  src/commands/registration/rnto.js
  src/connection.js
  test/commands/registration/rnto.spec.js
Labels: feature

#143 feat: remove host resolution
  .circleci/config.yml
  .eslintignore
  .gitignore
  CONTRIBUTING.md
  LICENSE
  README.md
  bin/index.js
  config/release/commitMessageConfig.js
  config/testUnit/mocha.opts
  config/testUnit/reporters.json
  config/verify/.eslintrc
  meta/contributors/contributors.js
  meta/logo/generate.js
  meta/logo/logo.html
  package-lock.json
  package.json
  src/commands/registration/pasv.js
  src/helpers/find-port.js
  src/helpers/resolve-host.js
  src/index.js
  test/connector/active.spec.js
  test/connector/passive.spec.js
  test/helpers/find-port.spec.js
  test/helpers/resolve-host.spec.js
  test/index.spec.js
  test/start.js
Labels: feature, in progress

#153 feat: remove pasv url resolution
  .circleci/config.yml
  .eslintignore
  .gitignore
  CONTRIBUTING.md
  LICENSE
  README.md
  bin/index.js
  config/release/commitMessageConfig.js
  config/testUnit/mocha.opts
  config/testUnit/reporters.json
  config/verify/.eslintrc
  meta/contributors/contributors.js
  meta/logo/generate.js
  meta/logo/logo.html
  package-lock.json
  package.json
  src/commands/registration/pasv.js
  src/helpers/find-port.js
  src/helpers/resolve-host.js
  src/index.js
  test/connector/active.spec.js
  test/connector/passive.spec.js
  test/helpers/find-port.spec.js
  test/helpers/resolve-host.spec.js
  test/index.spec.js
  test/start.js
Labels: breaking, feature
