Repository autovance/ftp-srv, pull requests merged in 2020-12, with the labels that each got.

#222 fix: ensure commandSocket is set before retrieving ip address of connection
  src/connection.js
Labels: bug

#224 fix(fs): check resolved path against root
  src/fs.js
  test/fs.spec.js
  test/start.js
Labels: bug, security

#227 chore: improve ci flows
  .circleci/config.yml
  package.json
Labels: chore
